
type User {
  uid: String
  fullName: String
  username: String
  password: String
  posts: [Post]
}

type Post {
  id: Int
  title: String
  body: String
}

input UserInput {
  fullName: String
  username: String
  password: String
}

type UserExists {
  message: String!
  username: String
}

union UserOrPostRes = User | Post 
union UserResult = User | NotFound | BadUserInput | Unauthorized | InternalServerError
union CreateUserResult = User | BadUserInput | InternalServerError | UserExists

type Query {
  getUsers: [User]
  getUser(username: String!, password: String!): UserResult
  getUserOrPost(id: String!): UserOrPostRes
}

type Mutation {
  createUser(form:UserInput!): CreateUserResult
}